language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - sh -c 'if [ $(php -r "echo (int) defined(\"HHVM_VERSION\");") -eq 0 ]; then pecl install channel://pecl.php.net/xhprof-0.9.3; fi'
  - COMPOSER_ROOT_VERSION=dev-master composer selfupdate
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  allow_failures:
    - php: hhvm
